### ISSUE TITLE
This library doesn't seems be working for banned-modules

### ISSUE THREAD

**Issue by harshit98** [adamchainz/flake8-tidy-imports#502]
### Python Version

3.9.0

### flake8 Version

3.8.3

### Description

Tried setting up the module. I've configured the following - `.flake8` and `.pre-commit-config.yaml`

.flake8

```
[flake8]
max-line-length = 80
max-complexity = 18
select = B,C,E,F,W,T4,B9,I125
ignore = B008, B903, B904, C901, E203, E266, E501, F401, F403, F541, W503
ban-relative-imports = true
banned-modules =
    json = use utils.msgspec
    elasticsearch = dont
require-plugins =
    flake8-implicit-str-concat
    flake8-bugbear
    flake8-tidy-imports==4.10.0
```

and .pre-commit-config-.yaml

```
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-implicit-str-concat
          - flake8-tidy-imports==4.10.0
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: (\.txt)$
```

When I try to `import json` in a file and commit, it commits easily and pushed. The expected behaviour should have been that if json library is imported - it should not commit (as per above details in .flake8) and raise error.
